"""empty message

Revision ID: 17f1f59a7539
Revises: 
Create Date: 2021-11-18 16:35:13.330419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f1f59a7539'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.LargeBinary(length=128), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('createdById', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('firstName', sa.String(length=30), nullable=True),
    sa.Column('lastName', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['createdById'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('studyGroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.LargeBinary(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountId', sa.Integer(), nullable=True),
    sa.Column('treatmentStarted', sa.Date(), nullable=False),
    sa.Column('treatmentFinished', sa.Date(), nullable=False),
    sa.Column('treatmentGoal', sa.String(length=280), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['accountId'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accountId'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patientTrainingZones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patientId', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('creationDate', sa.Date(), nullable=False),
    sa.Column('workoutType', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('upper0Bound', sa.Integer(), nullable=False),
    sa.Column('upper1Bound', sa.Integer(), nullable=False),
    sa.Column('upper2Bound', sa.Integer(), nullable=False),
    sa.Column('upper3Bound', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patientId'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plannedWorkouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('plannedDate', sa.Date(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('maxHeartRate', sa.Integer(), nullable=True),
    sa.Column('minDuration', sa.Integer(), nullable=True),
    sa.Column('minDistance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patientId'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patientId'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studyGroupPatients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studyGroupId', sa.Integer(), nullable=False),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patientId'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['studyGroupId'], ['studyGroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studyGroupTrainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studyGroupId', sa.Integer(), nullable=False),
    sa.Column('trainerId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['studyGroupId'], ['studyGroups.id'], ),
    sa.ForeignKeyConstraint(['trainerId'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appleUUID', sa.String(length=50), nullable=False),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=False),
    sa.Column('endTime', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(decimal_return_scale=3), nullable=True),
    sa.Column('terrainUp', sa.Float(decimal_return_scale=3), nullable=True),
    sa.Column('terrainDown', sa.Float(decimal_return_scale=3), nullable=True),
    sa.Column('heartRateAvg', sa.Float(decimal_return_scale=3), nullable=True),
    sa.Column('heartRateMin', sa.Integer(), nullable=True),
    sa.Column('heartRateMax', sa.Integer(), nullable=True),
    sa.Column('speedAvg', sa.Float(decimal_return_scale=3), nullable=True),
    sa.Column('speedMin', sa.Float(decimal_return_scale=3), nullable=True),
    sa.Column('speedMax', sa.Float(decimal_return_scale=3), nullable=True),
    sa.Column('paceMin', sa.Float(decimal_return_scale=3), nullable=True),
    sa.Column('paceMax', sa.Float(decimal_return_scale=3), nullable=True),
    sa.Column('trainingZones', sa.LargeBinary(), nullable=True),
    sa.Column('heartRateSamples', sa.LargeBinary(), nullable=True),
    sa.Column('speedSamples', sa.LargeBinary(), nullable=True),
    sa.Column('altitudeSamples', sa.LargeBinary(), nullable=True),
    sa.Column('distanceSamples', sa.LargeBinary(), nullable=True),
    sa.Column('kilometerPace', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['patientId'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rawWorkout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workoutId', sa.Integer(), nullable=False),
    sa.Column('healthKitJson', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['workoutId'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workoutRatings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workoutId', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=280), nullable=True),
    sa.ForeignKeyConstraint(['workoutId'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workoutRatings')
    op.drop_table('rawWorkout')
    op.drop_table('workouts')
    op.drop_table('studyGroupTrainers')
    op.drop_table('studyGroupPatients')
    op.drop_table('steps')
    op.drop_table('plannedWorkouts')
    op.drop_table('patientTrainingZones')
    op.drop_table('trainers')
    op.drop_table('roles')
    op.drop_table('patients')
    op.drop_table('users')
    op.drop_table('studyGroups')
    op.drop_table('accounts')
    # ### end Alembic commands ###
